### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lazerwalker** [dwd31415/Torch7iOSExample#1]
Hey Adrian!

I’m working on an iOS project that uses Torch, and I found your blog post / tutorial about getting torch-iOS set up to be super-helpful. Thanks for that!

I’m working on setting up a CocoaPod that contains a pre-built version of Torch.framework for folks to more easily pull into their own projects. I’d love to include your `TorchInterface.h/m` boilerplate from this repo as an interface, but I noticed this repo doesn't have an open-source license.

Are you okay with me using your code in this way? Either way, it would be awesome if you wanted to update this repo with a license, so other folks can know how you feel about them using your code. 

(I don't want to presume any knowledge or lack thereof, but if this is something that's new to you I'm also more than happy to help you pick an appropriate license)

**Comment by dwd31415** [comment]
I have absolutely no problem with you using the code from this repository in your project, indeed I think a CocoaPod for this would be very convenient. 
I have added an MIT License to this repository, as I originally intended, but apparently forgot to do.

**Comment by lazerwalker** [comment]
Thanks for the quick response! 

If you're curious, will drop you a line when I get something pushed. Currently mucking around with what the build pipeline actually looks like (since I personally need some third-party torch libraries that aren't included in the existing torch-ios build), and then there's some thinking to be done about what the best way to actually distribute it is (i.e. when is distributing the precompiled .framework a bad idea?), but will hopefully happen sooner than later.
